[package]
name = "host"
version = "0.1.0"
edition = "2021"
categories = ["wasm"]

[dependencies]
wasm-bindgen = "0.2.58"
console_error_panic_hook = "0.1.6"

[dependencies.web-sys]
version = "0.3.63"
features = ["Document", "Element", "HtmlElement", "Node", "Window", "console"]
